# Generated by Django 4.0.4 on 2022-08-01 12:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('R', 'Rejected'), ('D', 'Deliverd')], max_length=1, verbose_name='Order status')),
                ('items', models.JSONField(blank=True, null=True, verbose_name='items')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, help_text='in KWD', max_digits=10, verbose_name='total_price')),
                ('order_date', models.DateField(blank=True, verbose_name='order date')),
                ('order_time', models.TimeField(blank=True, verbose_name='order time')),
                ('completed', models.BooleanField(verbose_name='Customer completed order')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200, verbose_name='full name')),
                ('email', models.EmailField(blank=True, help_text='optional', max_length=100, null=True, verbose_name='email')),
                ('phone_number', models.CharField(help_text='+965 ---- ----', max_length=15, null=True, verbose_name='Phone number')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('street', models.CharField(max_length=100, verbose_name='Street')),
                ('building', models.CharField(max_length=100, verbose_name='Building')),
                ('details', models.TextField(verbose_name='More details')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'Shipping address',
                'verbose_name_plural': 'Shipping addresses',
            },
        ),
    ]
